name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "40 1 * * 1"  # every Monday at 01:40 UTC

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Compile and Lint
        run: npm run compile

